version: "3.8"
services:
  postgres:
    container_name: postgres-db
    image: postgres:alpine
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tupolord
      POSTGRES_DB: postgres
    volumes:
    - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: app
    ports:
      - 9999:8000
    depends_on:
      - postgres

volumes:
  postgres-data:
    driver: local
