"""database creation1

Revision ID: 4ef4e2d44cc3
Revises: 3743db693bff
Create Date: 2024-10-03 15:26:47.619917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ef4e2d44cc3'
down_revision: Union[str, None] = '3743db693bff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banks', sa.Column('bank_name', sa.String(), nullable=False))
    op.drop_column('banks', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banks', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('banks', 'bank_name')
    # ### end Alembic commands ###
