"""database_custom

Revision ID: 9d563d30b8a4
Revises: d0a8d97c4689
Create Date: 2024-10-10 13:50:46.568698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d563d30b8a4'
down_revision: Union[str, None] = 'd0a8d97c4689'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('custom_name', sa.String(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custom')
    # ### end Alembic commands ###
