"""BD_1

Revision ID: e45d0287c974
Revises: 9d563d30b8a4
Create Date: 2024-10-20 14:07:52.276363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e45d0287c974'
down_revision: Union[str, None] = '9d563d30b8a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'custom', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'custom', type_='foreignkey')
    op.drop_column('custom', 'user_id')
    # ### end Alembic commands ###
